# netlify.toml — opțional (nu e necesar pentru formulare simple)
[build]
  publish = "."

# Exemplu de redirecționare pentru SPA (dacă adaugi rute client-side)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
